#!/usr/bin/env node
// The checked-in expected outputs: their provenance and how they are
// regenerated.
//
// 1. Generated once (a6575ff8) from the fork's Rust compiler while it carried
//    the block rule (packages/compiler/src/blocks_rule.rs and its
//    tests/blocks-rule-fixtures.json): rule.json (the cases, with the
//    compiler's message for each refusal), twins/ (one source file per JSX
//    twin), compiled/*.out (the compiler's output for each accepted case and
//    each twin sample). The plugin's output, compiled, reproduced every one of
//    them byte for byte. That script is `git show a6575ff8:packages/vite-plugin-blocks/test/fixtures/generate.mjs`.
// 2. D-043 removed the rule from the compiler, and the plugin's `perform`
//    import moved onto the line it precedes (no line shift; D-031 note). The
//    compiled outputs were regenerated by this script: the workspace compiler
//    (upstream, no rule) over the plugin's output. Diffed against (1): 16 of
//    the 26 outputs are identical; in the other 10 the one change is that the
//    import line comes after the module's leading comments instead of before
//    them (it is placed just before the first statement). The
//    refusal messages in rule.json and the twins/ snapshots are kept as the
//    Rust rule left them; they are the oracle now (D-043).
//
//   node test/fixtures/generate.mjs   (from packages/vite-plugin-blocks)
//
// Rewrites compiled/accepted-<n>.<mode>.out and compiled/<twin>.<mode>.out,
// where <mode> is `dom` (default options) or `ssr` (`generate: "ssr"`,
// `hydratable: true`). Run it only for a deliberate change of the plugin's
// output, and review the diff.
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const compiler = require("@solidjs/compiler");
const { transform } = await import("../../src/index.js");

export const MODES = {
  dom: {},
  ssr: { generate: "ssr", hydratable: true }
};

/** One source file per JSX twin: the one with the most holes. */
export const TWIN_SAMPLES = {
  "effect-blocks": "src/checkout.tsx",
  "hackernews-spa-blocks": "src/components/story.tsx",
  "rendering-blocks": "shared/src/components/App.tsx",
  "room-blocks": "src/routes/live.tsx",
  "sierpinski-blocks": "src/app.tsx",
  "todos-blocks": "src/app.tsx"
};

/** The file name the compiler is given for a twin sample (stable across machines). */
export const twinFilename = (twin, file) => `${twin}/${basename(file)}`;

function main() {
  const probe = compiler.transform("function* v() { return <p>{yield* n}</p>; }", {
    filename: "probe.tsx"
  }).code;
  if (probe.includes("perform")) {
    console.error("generate.mjs: the workspace compiler still carries a block rule (D-043)");
    process.exit(1);
  }
  const compile = (code, filename, mode) => {
    const out = transform(code, { filename, lazy: false });
    return compiler.transform(out ? out.code : code, { filename, ...MODES[mode] }).code;
  };
  const rule = JSON.parse(readFileSync(join(here, "rule.json"), "utf8"));
  rule.accepted.forEach((src, i) => {
    for (const mode of Object.keys(MODES))
      writeFileSync(
        join(here, `compiled/accepted-${i}.${mode}.out`),
        compile(src, "case.tsx", mode)
      );
  });
  for (const [twin, file] of Object.entries(TWIN_SAMPLES)) {
    const code = readFileSync(join(here, "twins", twin, basename(file)), "utf8");
    for (const mode of Object.keys(MODES))
      writeFileSync(
        join(here, `compiled/${twin}.${mode}.out`),
        compile(code, twinFilename(twin, file), mode)
      );
  }
  console.log("generate.mjs: rewrote compiled/*.out");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
