/**
 * The coverage matrix (COVERAGE.md), generated from the scenario and mode
 * registries so the documented coverage cannot drift from what runs.
 */
import { compile } from "./module.js";
import { modes, absentModes } from "./modes.js";
import { exclusion, expectationFor } from "./register.js";
import { dropped, routeFindings } from "../scenarios/index.js";
import type { Scenario } from "./types.js";

const CELL = {
  oracle: "oracle",
  equivalent: "=",
  differs: "≠ declared",
  "known-defect": "✗ defect",
  "not-applicable": "n/a"
} as const;

export function coverageMatrix(scenarios: Scenario[]): string {
  const out: string[] = [];
  const short = (id: string) =>
    id.replace("client/", "c/").replace("server/", "s/").replace("hydrate/", "h/");
  out.push("# Semantic conformance coverage");
  out.push("");
  out.push(
    "Generated by `test/conformance/conformance.spec.ts` (update with `vitest -u`). " +
      "`=` equivalent to the oracle of the same environment; `≠ declared` an intentional difference with an exact expected trace; " +
      "`✗ defect` a pinned defect (must keep diverging); `n/a` not applicable; `–` not run (client-only scenario)."
  );
  out.push("");
  out.push(`| scenario | ${modes.map(m => short(m.id)).join(" | ")} |`);
  out.push(`| --- | ${modes.map(() => ":-:").join(" | ")} |`);
  const notes = new Map<string, Set<string>>();
  for (const scenario of scenarios) {
    const cells = modes.map(mode => {
      const excluded = exclusion(scenario, mode);
      const expectation = expectationFor(scenario, mode);
      const runs = !excluded || expectation.status === "not-applicable";
      if (runs && expectation.status !== "equivalent") {
        const reason = "reason" in expectation ? expectation.reason : "";
        const key = `${CELL[expectation.status]}: ${reason}`;
        if (!notes.has(key)) notes.set(key, new Set());
        notes.get(key)!.add(`${scenario.name} (${mode.id})`);
      }
      if (!runs) return "–";
      if (!mode.reference) return CELL.oracle;
      return CELL[expectation.status];
    });
    out.push(`| ${scenario.name} | ${cells.join(" | ")} |`);
  }
  out.push("");
  out.push("## Declared differences, defects and exclusions");
  out.push("");
  for (const [note, where] of notes) {
    out.push(`- **${note}**`);
    out.push(`  - ${[...where].join(", ")}`);
  }
  out.push("");
  out.push("## Library route vs compiler route (server output)");
  out.push("");
  out.push(
    "`routes.spec.ts` compares `server/library`'s output with the compiler route's (`__artifacts__/compiler-route/`, the fork's `server/blocks-compiled`, frozen). Every difference is a finding, recorded in DECISIONS.md:"
  );
  out.push("");
  for (const finding of routeFindings)
    out.push(`- **${finding.scenario}** (${finding.decision}): ${finding.summary}`);
  out.push("");
  out.push("## What the library route ran (compiled output facts)");
  out.push("");
  out.push(
    "`function*` bodies left (every one interpreted by the runtime) / `_$perform(` holes the block rule wrote, in the client build of the library source."
  );
  out.push("");
  out.push("| scenario | c/library |");
  out.push("| --- | --- |");
  for (const scenario of scenarios) {
    const source = scenario.sources.library;
    let cell = "–";
    if (source !== undefined) {
      try {
        const { stats } = compile(source, "library", { generate: "dom" });
        cell = `${stats.generators} / ${stats.performs}`;
      } catch (error) {
        cell = `compile error: ${(error as Error).message.split("\n", 1)[0]}`;
      }
    }
    out.push(`| ${scenario.name} | ${cell} |`);
  }
  out.push("");
  out.push("## Semantic areas");
  out.push("");
  for (const scenario of scenarios)
    out.push(`- **${scenario.name}**: ${scenario.covers.join("; ")}`);
  out.push("");
  out.push("## Not ported");
  out.push("");
  for (const d of dropped) out.push(`- **${d.name}**: ${d.why}`);
  for (const m of absentModes) out.push(`- \`${m.id}\` — ${m.title}: ${m.why}`);
  out.push("");
  return out.join("\n");
}
