/**
 * The library route against the compiler route (D-039). The compiler route's
 * server output for the three row scenarios — the fork's
 * `server/blocks-compiled` artifacts, generated by its blocks compiler — is
 * kept frozen under `__artifacts__/compiler-route/`. Each is compared with
 * `server/library`'s pinned output. A difference is a finding: it must be
 * declared in `scenarios/declared.ts` (`routeFindings`) exactly — both key
 * lists, and the markup only one route emits — and recorded in DECISIONS.md.
 * Nothing is normalized away: once the declared keys are replaced by their
 * ordinals and the declared compiler-only markup is removed, the two outputs
 * must be byte-identical.
 */
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { describe, expect, test } from "vitest";
import { artifactFile, artifactsDir, compilerRouteFile } from "./harness/artifacts.js";
import { routeFindings } from "./scenarios/index.js";

const keys = (html: string) => [...html.matchAll(/\s_hk=([^\s>]+)/g)].map(m => m[1]);
/** Keys replaced by their ordinals; each declared fragment removed exactly `n` times. */
function skeleton(html: string, drop: Record<string, number> = {}): string {
  let i = 0;
  let out = html.replace(/(\s_hk=)[^\s>]+/g, (_, attr: string) => `${attr}#${i++}`);
  for (const [fragment, n] of Object.entries(drop)) {
    const parts = out.split(fragment);
    expect(parts.length - 1, `occurrences of ${fragment}`).toBe(n);
    out = parts.join("");
  }
  return out;
}

const scenarios = readdirSync(`${artifactsDir}/compiler-route`)
  .map(file => file.replace(/\.server-blocks-compiled\.html$/, ""))
  .sort();

describe("library route vs compiler route (server output)", () => {
  test("every compiler-route artifact has a library counterpart", () => {
    expect(scenarios.length).toBe(3);
    for (const s of scenarios) expect(existsSync(artifactFile(s, "server/library")), s).toBe(true);
  });

  for (const scenario of scenarios)
    test(scenario, () => {
      const compiler = readFileSync(compilerRouteFile(scenario), "utf8");
      const library = readFileSync(artifactFile(scenario, "server/library"), "utf8");
      const finding = routeFindings.find(f => f.scenario === scenario);
      if (compiler === library) {
        expect(finding, `${scenario}: the routes agree now; remove its finding`).toBeUndefined();
        return;
      }
      expect(finding, `${scenario}: an undeclared difference between the routes`).toBeDefined();
      expect(keys(compiler)).toEqual(finding!.compilerKeys);
      expect(keys(library)).toEqual(finding!.libraryKeys);
      expect(skeleton(library)).toBe(skeleton(compiler, finding!.compilerOnly));
    });
});
