import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { docsPayload } from "../../../packages/compiler-yield/src/reachability-data.js";
import { feed, item, user } from "../../hackernews-spa-yield/tests/fixtures/hn-data.mjs";
const repo = resolve(import.meta.dirname, "../../..");
const temp = mkdtempSync(join(tmpdir(), "c1b-data-"));
try {
  const html = join(temp, "docs.html");
  const run = spawnSync(
    process.execPath,
    ["--test", "packages/compiler-yield/test/eager-docs.test.mjs"],
    {
      cwd: repo,
      encoding: "utf8",
      timeout: 30000,
      env: {
        ...process.env,
        NODE_ENV: "production",
        C2_DOCS_MODE: "library",
        C2_SSR_ONLY: "1",
        C2_PRODUCTION: "1",
        C2_HTML: html
      }
    }
  );
  if (run.status !== 0) throw new Error(run.stdout + run.stderr);
  const result = {
    sources: {
      docs: "completed library SSR, generated by eager-docs.test.mjs C2_SSR_ONLY=1 C2_PRODUCTION=1 at /",
      hn: "examples/hackernews-spa-yield/tests/fixtures/hn-data.mjs: feed(top,1), item(job-3), user(alice)"
    },
    ...docsPayload(readFileSync(html, "utf8")),
    hnFeed: feed("top", 1),
    hnStory: item("job-3"),
    hnUser: user("alice")
  };
  const i = process.argv.indexOf("--record");
  if (i >= 0) writeFileSync(process.argv[i + 1], JSON.stringify(result, null, 2) + "\n");
  console.log(`SSR payload extracted; HN deterministic data copied; SSR hash ${result.htmlSHA256}`);
} finally {
  rmSync(temp, { recursive: true, force: true });
}
